name: CI/CD

on:
  push:
    branches:    
    - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: Get poetry
        run: |
          pip install poetry==1.1.5
      - name: install project dependencies
        run: |
          poetry install
      - name: Check code formatting
        run: |
          poetry run fmt-check
      - name: Check import orders
        run: |
          poetry run isort-check
      - name: Linter
        run: |
          poetry run linter
      - name: Run tests
        run: |
          poetry run tests
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
          registry: docker.pkg.github.com
          repository: itsmeale/covid_cajamar/covid_cajamar
          tag_with_ref: true
